POST http://localhost:5000/api/short
Content-Type: application/json

{
    "longUrl": "https://www.google.com/search?q=gatherly&sxsrf=AOaemvLGpt9VEWQqVyZ6JM9U3PAZm0hvCA%3A1634103705830&source=hp&ei=mXFmYaKGMM2q_QbZtaKQBQ&iflsig=ALs-wAMAAAAAYWZ_qXdohcnHWQXyDaEvU9NMmZqvZEo4&ved=0ahUKEwjitqPX1sbzAhVNVd8KHdmaCFIQ4dUDCAg&uact=5&oq=gatherly&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBAgjECcyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgcIABCABBAKOgcIIxDqAhAnOgUIABCRAjoICAAQgAQQsQM6DgguEIAEELEDEMcBENEDOgsIABCABBCxAxCDAToOCC4QgAQQsQMQxwEQowI6CAguELEDEIMBOgsILhCABBDHARCvAToICC4QgAQQsQM6DgguEIAEELEDEMcBEK8BUJ0SWMUYYP0ZaABwAHgAgAHUAogBwQ2SAQcwLjUuMi4xmAEAoAEBsAEK&sclient=gws-wiz"
}